DROP TABLE IF EXISTS users, items, requests, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(50) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS  item_requests (
 id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 description VARCHAR(255),
 requestor_id INT NOT NULL,
 created timestamp NOT NULL,
 CONSTRAINT pk_item_requests PRIMARY KEY (id),
 CONSTRAINT fk_item_requests_to_users FOREIGN KEY(requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  owner_id INT NOT NULL,
  description VARCHAR(255),
  is_available BOOLEAN NOT NULL,
  request_id INT,
  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id) REFERENCES users(id),
  CONSTRAINT fk_items_to_request FOREIGN KEY(request_id) REFERENCES item_requests(id)
);

CREATE TABLE IF NOT EXISTS requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description varchar(512) NOT NULL,
    requesting_user_id integer REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id integer REFERENCES items(id) ON DELETE CASCADE,
    booker_id integer REFERENCES users(id) ON DELETE CASCADE,
    status varchar(10) NOT NULL DEFAULT 'WAITING'
);

CREATE TABLE IF NOT EXISTS comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text varchar(5000),
    item_id integer REFERENCES items(id) ON DELETE CASCADE,
    author_id integer REFERENCES users(id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE
);